using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Threading.Tasks;
using Module.UserDataSetTableAdapters;//Importing the Namespace(From Autogenerated code) to access data

namespace Module
{
    public class UserDAO
    {
        public User UserLogin(string UserName, string Password)
        {
            TabUserTableAdapter tabUserTableAdapter = new TabUserTableAdapter();

            UserDataSet.TabUserDataTable tabUserDataTable = tabUserTableAdapter.UserLogin(UserName, Password);

            if (tabUserDataTable != null && tabUserDataTable.Count > 0)
            {
                // to get the first row from the data table if a user is found
                var row = tabUserDataTable[0];
                User user = new User
                {
                    UserName1 = UserName, // Set the username
                    Password1 = Password, // Set the password
                    UserLevel1 = Convert.ToInt32(row["UserLevel"]), // Setting the userlevel after converting it from string to int
                    UserId1 = Convert.ToInt32(row["UID"])
                };

                return user; // Returning the constructed user
            }
            else
            {
                // Handleling the case where no user is found or password does not match
                return null;
            }


        }
        public int UpdatePasswords(string NewPassword, int UID, string Original_Password)
        {

            TabUserTableAdapter tabUserTableAdapter = new TabUserTableAdapter();

           int istatusUP = tabUserTableAdapter.UpdatePasswords(NewPassword, UID, Original_Password);


            return istatusUP;
        }

    }
       




}
    

    

